In [1]:
import numpy as np 
import pandas as pd 
import matplotlib
from matplotlib import pyplot as plt 
from sklearn.linear_model import LinearRegression 

In [2]:
df = pd.DataFrame({
    "x" :[1,2,3],
    "y" : [1,3,4],
    "z" : [2 ,1 ,5]
})

In [3]:
df

x  y  z
0  1  1  2
1  2  3  1
2  3  4  5

In [4]:
class multiLR :

    def __init__(self):
        self.coef_ = None 
        self.intercept_ = None 
        self.pred_ = None 
        
    def fit (self , X , y ):
        X = np.insert(X , 0 , 1 , axis = 1 )

        weights = np.linalg.inv((X.T@X))@(np.transpose(X))@y
        self.intercept_ = weights[0]
        self.coef_  = weights[1:]

    def predict(self, X):
        self.pred_ = np.dot(X,self.coef_) + self.intercept_
        
        
        

In [5]:
mullr = multiLR()

In [6]:
X = df.drop(columns=["z"])
y = df["z"]

In [7]:
mullr.fit(X,y)

In [8]:
mullr.coef_

array([ 9., -5.])

In [9]:
mullr.intercept_

np.float64(-2.0000000000002345)

In [10]:
mullr.predict(X)

In [11]:
mullr.pred_

array([2., 1., 5.])

In [16]:
import plotly.express as px
import plotly.graph_objects as go

In [20]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"

In [50]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model
mullr.predict(grid)
Z_pred = mullr.pred_
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [24]:
lr = LinearRegression()

In [25]:
lr.fit(X,y)

LinearRegression()

In [26]:
lr.intercept_

np.float64(-1.9999999999999996)

In [27]:
lr.coef_

array([ 9., -5.])

In [51]:
# AS we see that coefficient and intercept are nearly similar 

In [33]:
# r2_score
lr.score(X,lr.predict(X))

1.0

In [34]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [36]:
df = pd.DataFrame({'x':X[:,0],'y':X[:,1],'z':y})

In [37]:
df.head()

x         y           z
0 -2.045881  0.803405 -241.976777
1 -0.776167 -1.798236 -205.418462
2 -0.645282  1.216718   18.986363
3 -1.357822 -0.931741 -159.347277
4 -0.926197  1.461213  -42.003854

In [38]:
df.shape

(100, 3)

In [39]:
X = df.drop("z" , axis = 1)
y = df["z"]

In [42]:
mlr = multiLR()

In [43]:
mlr.fit(X,y)

In [45]:
mlr.predict(X)

In [46]:
mlr.coef_

array([62.12619186, 23.81394668])

In [47]:
mlr.intercept_

np.float64(-9.569766456018257)

In [48]:
mlr2 = LinearRegression()
mlr2.fit(X,y)

LinearRegression()

In [49]:
mlr.coef_ , mlr.intercept_

(array([62.12619186, 23.81394668]), np.float64(-9.569766456018257))

In [52]:
# hence both have similar results 


In [53]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model
mullr.predict(grid)
Z_pred = mullr.pred_
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [54]:
mlr2.predict([[-2.045881,0.8034048]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([-117.54032292])