In [7]:
import numpy as np 
import pandas as pd 
import matplotlib
from matplotlib import pyplot as plt 
from sklearn.linear_model import LinearRegression 

In [4]:
df = pd.DataFrame({
    "x" :[1,2,3],
    "y" : [1,3,4],
    "z" : [2 ,1 ,5]
})

In [3]:
df

x  y  z
0  1  1  2
1  2  3  1
2  3  4  5

In [8]:
class multiLR :

    def __init__(self):
        self.coef_ = None 
        self.intercept_ = None 
        
        
    def fit (self , X , y ):
        X = np.insert(X , 0 , 1 , axis = 1 )
        
        #β* = (X_transposeX)-¹X_transposey
        weights = np.linalg.inv((X.T@X))@(np.transpose(X))@y
        self.intercept_ = weights[0]
        self.coef_  = weights[1:]

    def predict(self, X):
        return np.dot(X,self.coef_) + self.intercept_
        
        
        

In [5]:
mullr = multiLR()

In [6]:
X = df.drop(columns=["z"])
y = df["z"]

In [7]:
mullr.fit(X,y)

In [8]:
mullr.coef_

array([ 9., -5.])

In [9]:
mullr.intercept_

np.float64(-2.0000000000002345)

In [10]:
mullr.predict(X)

array([2., 1., 5.])

In [11]:
import plotly.express as px
import plotly.graph_objects as go

In [12]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"

In [13]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model

Z_pred = mullr.predict(grid)
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [14]:
lr = LinearRegression()

In [15]:
lr.fit(X,y)

LinearRegression()

In [16]:
lr.intercept_

np.float64(-1.9999999999999996)

In [17]:
lr.coef_

array([ 9., -5.])

In [18]:
# AS we see that coefficient and intercept are nearly similar 

In [19]:
# r2_score
lr.score(X,lr.predict(X))

1.0

In [20]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [21]:
df = pd.DataFrame({'x':X[:,0],'y':X[:,1],'z':y})

In [22]:
df.head()

x         y          z
0 -0.709934  0.768004 -36.757301
1  0.272000 -0.809650 -49.477953
2  0.769715  1.811370  66.114838
3 -1.597092  0.266716 -88.808810
4  0.642167  0.074982  22.833085

In [23]:
df.shape

(100, 3)

In [24]:
X = df.drop("z" , axis = 1)
y = df["z"]

In [25]:
mlr = multiLR()

In [26]:
mlr.fit(X,y)

In [27]:
mlr.predict(X)

array([  11.01882405,  -29.65972369,  148.59822333,  -64.24412949,
         41.01517947,    9.40766712,   65.58158727,   82.93380449,
        149.4688966 ,   52.67030363,  -69.48315868,  187.52587157,
        -70.50303712,  -92.12695712,   67.19267285,  -22.15293196,
        -40.68980516,  -94.77507188,   18.0397538 ,  -51.76552485,
         32.21392325,  -41.66127841,  100.43426627,   14.96669575,
         42.66616018,  -27.34953011,   83.26547712,  125.20240423,
        -31.38302296,  100.64360633, -117.65776582,  127.69111074,
         62.16374489,  -92.22692576,  -23.21397058,  110.83300182,
        -41.49749094,  -28.71052696,    4.60172126,  105.76986699,
         70.28064812, -157.38684672,  -84.09295526,  -45.8731696 ,
          3.71800318,  -32.78540261,  193.57111596,  -67.15985053,
         42.80973489, -225.14865211,   12.29857727,  -88.16996931,
        148.73160554,   59.62180355,  -43.18604672,  134.61521837,
        -18.52314316,  144.55399405,  124.0746279 ,  -22.42310

In [28]:
mlr.coef_

array([51.98445201, 58.13937332])

In [29]:
mlr.intercept_

np.float64(3.273094928910539)

In [30]:
mlr2 = LinearRegression()
mlr2.fit(X,y)

LinearRegression()

In [31]:
mlr.coef_ , mlr.intercept_

(array([51.98445201, 58.13937332]), np.float64(3.273094928910539))

In [32]:
# hence both have similar results 


In [33]:
mlr2.predict([[-2.045881,0.8034048]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([-56.37145615])

In [35]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model

Z_pred = mlr.predict(grid)
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [54]:
import os
os.getcwd()


'C:\\Users\\HP\\Work Fullstack\\ML aglo from scratch\\notebooks\\Linear_regression'

In [5]:
from pathlib import Path 
Path.cwd()

WindowsPath('C:/Users/HP/Work Fullstack/ML aglo from scratch/notebooks/Linear_regression')

In [9]:
# Applying multiple linear regression  on simple dataset/2d dataset

df = pd.read_csv(r'c:/Users/HP/Work Fullstack/ML aglo from scratch/data/placement.csv')

In [10]:
lr = multiLR()


In [11]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [27]:
X = df["cgpa"].values.reshape(-1, 1)
y = df["package"]

In [28]:
lr.fit(X,y)

In [30]:
y_pred = lr.predict(X)

In [34]:
from sklearn.metrics import r2_score 
r2_score( y_pred, y)
# this one is wrong because r2_score expect y_true in first argument 

0.7107075650170644

In [35]:
r2_score(y , y_pred)

0.7756192256051151