In [37]:
import numpy as np 
import pandas as pd 
import matplotlib
from matplotlib import pyplot as plt 
from sklearn.linear_model import LinearRegression 

In [38]:
df = pd.DataFrame({
    "x" :[1,2,3],
    "y" : [1,3,4],
    "z" : [2 ,1 ,5]
})

In [39]:
df

x  y  z
0  1  1  2
1  2  3  1
2  3  4  5

In [40]:
class multiLR :

    def __init__(self):
        self.coef_ = None 
        self.intercept_ = None 
        self.pred_ = None 
        
    def fit (self , X , y ):
        X = np.insert(X , 0 , 1 , axis = 1 )

        weights = np.linalg.inv((X.T@X))@(np.transpose(X))@y
        self.intercept_ = weights[0]
        self.coef_  = weights[1:]

    def predict(self, X):
        self.pred_ = np.dot(X,self.coef_) + self.intercept_
        
        
        

In [41]:
mullr = multiLR()

In [42]:
X = df.drop(columns=["z"])
y = df["z"]

In [43]:
mullr.fit(X,y)

In [44]:
mullr.coef_

array([ 9., -5.])

In [45]:
mullr.intercept_

np.float64(-2.0000000000002345)

In [46]:
mullr.predict(X)

In [47]:
mullr.pred_

array([2., 1., 5.])

In [48]:
import plotly.express as px
import plotly.graph_objects as go

In [49]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"

In [50]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model
mullr.predict(grid)
Z_pred = mullr.pred_
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [51]:
lr = LinearRegression()

In [52]:
lr.fit(X,y)

LinearRegression()

In [53]:
lr.intercept_

np.float64(-1.9999999999999996)

In [54]:
lr.coef_

array([ 9., -5.])

In [55]:
# AS we see that coefficient and intercept are nearly similar 

In [56]:
# r2_score
lr.score(X,lr.predict(X))

1.0

In [57]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [58]:
df = pd.DataFrame({'x':X[:,0],'y':X[:,1],'z':y})

In [59]:
df.head()

x         y          z
0  0.600158 -0.308468  45.478675
1  1.854013  0.500259  85.245129
2 -1.687435  0.086155  15.459154
3 -1.398971 -0.900404 -50.980595
4 -0.675999 -0.656146 -55.963008

In [60]:
df.shape

(100, 3)

In [61]:
X = df.drop("z" , axis = 1)
y = df["z"]

In [62]:
mlr = multiLR()

In [63]:
mlr.fit(X,y)

In [64]:
mlr.predict(X)

In [65]:
mlr.coef_

array([23.37182366, 55.02890046])

In [66]:
mlr.intercept_

np.float64(-1.4745626837977284)

In [67]:
mlr2 = LinearRegression()
mlr2.fit(X,y)

LinearRegression()

In [68]:
mlr.coef_ , mlr.intercept_

(array([23.37182366, 55.02890046]), np.float64(-1.4745626837977284))

In [69]:
# hence both have similar results 


In [70]:
mlr2.predict([[-2.045881,0.8034048]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([-5.08004988])