In [95]:
import numpy as np 
import pandas as pd 
import matplotlib
from matplotlib import pyplot as plt 
from sklearn.linear_model import LinearRegression 
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = "notebook_connected"
np.random.seed(42)

In [96]:
# solving sum mathematical conmfussion related to algo writing 
X = pd.DataFrame({
    "x" : [1,3],
    "y" : [2,4],
    "z" : [5,6]
})
w = [2,3,4]
y = [30,40]

# don't need to transpose manually , it managed by self with in np.dot() dot product via numpy 
np.dot(X,w), X.values @ w,  X @ w,X.dot(w) 


(array([28, 42]),
 array([28, 42]),
 0    28
 1    42
 dtype: int64,
 0    28
 1    42
 dtype: int64)

In [97]:
class LinearRegressionGD:

    def __init__(self, lr=0.01, epoches=50):
        self.lr = lr
        self.epoches = epoches
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X, y):
        X = np.insert(X, 0, 1, axis=1)
        weights = np.zeros(X.shape[1])

        for i in range(self.epoches):
            y_pred = X @ weights
            gradient = (X.T @ (y - y_pred)) / X.shape[0]
            weights = weights + self.lr * gradient

        self.intercept_ = weights[0]
        self.coef_ = weights[1:]

    def predict(self, X):
        return np.dot(X,self.coef_) + self.intercept_


In [98]:
my_lr = LinearRegressionGD()
sk_lr = LinearRegression()
my_lr.fit(X,y) , sk_lr.fit(X,y)
my_lr.predict(X), sk_lr.predict(X)

(array([29.07391475, 40.64536788]), array([30., 40.]))

In [99]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [100]:
my_lr = LinearRegressionGD(epoches = 100 , lr= 0.05)

In [101]:
my_lr.fit(X,y)
y_pred_my_lr = my_lr.predict(X)

In [102]:
df = pd.DataFrame({'x':X[:,0],'y':X[:,1],'z':y})
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model

Z_pred = my_lr.predict(grid)
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [103]:
sk_lr = LinearRegression()
sk_lr.fit(X,y)
y_pred_sk_lr = sk_lr.predict(X)
from sklearn.metrics import r2_score
r2_score(y,y_pred_sk_lr) ,r2_score(y,y_pred_my_lr)

(0.7819072511229945, 0.7816885200498906)

In [104]:
X_ = pd.DataFrame({
    "x" : [1,3],
    "y" : [2,4],
    "z" : [5,6]
})
w = [2,3,4]
y_ = [30,40]

# don't need to transpose manually , it managed by self with in np.dot() dot product via numpy 
print(np.dot(X_,w), X_.values @ w )
print(X_ @ w)
print(X_.dot(w))
X_

[28 42] [28 42]
0    28
1    42
dtype: int64
0    28
1    42
dtype: int64


x  y  z
0  1  2  5
1  3  4  6

In [105]:
X_.insert(0 , "new"  , np.ones(X_.shape[0]))

In [78]:
import numpy as np

class LinearRegressionSGD:

    def __init__(self, lr=0.01, epoches=10):
        self.lr = lr
        self.epoches = epoches
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X, y):
        # add bias term
        X = np.insert(X, 0, 1, axis=1)
        weights = np.zeros(X.shape[1])

        n = X.shape[0]

        for _ in range(self.epoches):
            for _ in range(n):
                r = np.random.randint(0, n)
                y_pred = X[r] @ weights
                error = y[r] - y_pred
                gradient = error * X[r]          # <-- vector gradient
                weights = weights + self.lr * gradient

        self.intercept_ = weights[0]
        self.coef_ = weights[1:]

    def predict(self, X):
        return X @ self.coef_ + self.intercept_        

In [79]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [87]:
sgd_lr = LinearRegressionSGD(epoches = 100)
sgd_lr.fit(X,y)
pred = sgd_lr.predict(X)
from sklearn.metrics import r2_score
r2_score(y,pred)

0.7388099735951574

In [91]:
# look result is so much bad so we first we need to normalize the data to get best results 
from sklearn.preprocessing  import StandardScaler 
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [94]:
sgd_lr = LinearRegressionSGD(epoches = 50)
sgd_lr.fit(X,y)
pred = sgd_lr.predict(X)
from sklearn.metrics import r2_score
r2_score(y,pred)

0.7366580853123803